version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html
      - ./certs:/etc/letsencrypt
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - 8000:8000
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql_latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: thewave
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1q2w3e4r
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
