version: "3.3"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
  client:
        networks:
            - app-tier
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        container_name: kiwi-frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
            - ../certbot/conf:/etc/letsencrypt # 추가
            - ../certbot/www:/var/www/certbot # 추가
        restart: always
        ports:
            - '80:80'
            - '443:443'
            - '3000:3000'
        expose:
            - '80'
            - '443'
            - '3000:3000'
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    certbot: # certbot 서비스 추가
        image: certbot/certbot
        container_name: certbot_service
        volumes:
            - ../certbot/conf:/etc/letsencrypt
            - ../certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  server:
    build: ./server
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
