version: "3.3"
services:
  server:
    build: ./server
    ports:
      - 8000:8000
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql_latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: thewave
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1q2w3e4r
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
